### ISSUE TITLE
being able to configure the PATH and the HMR to include other cosmos network

### ISSUE THREAD

**Issue by antoineherzog** [hukkinj1/cosmospy#10]
At starname (https://starname.me/), we would like to use this library however we need to customize so far the PATH and the HMR

**Comment by hukkinj1** [comment]
Hi @antoineherzog , thanks for the issue!

Does this commit do what you need? https://github.com/hukkinj1/cosmospy/commit/145c9bc6c417f96e43801689bed5efa7838e96b7

If yes, that's good, it is now released on PyPI (version 5.1.0).

**Comment by antoineherzog** [comment]
Yes I think so! thank you for your quick reply!
