### ISSUE TITLE
problem at broadcasting

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [hukkinj1/cosmospy#13]
hi. I use [this link](https://cosmos.network/rpc/v0.37.9) to post transaction created by this library. but when I paste the body of transaction at "POST/txs" I get the "TypeError: Failed to fetch" and when I use the curl command I get as a result the code of a HTML file. the transaction I'm trying to post is : 

{"tx":{"msg":[{"type":"cosmos-sdk/MsgSend","value":{"from_address":"cosmos1j32hpgtzh4sudpl0658ylr2tdzu65reyy78x50","to_address":"cosmos1j32hpgtzh4sudpl0658ylr2tdzu65reyy78x50","amount":[{"denom":"uatom","amount":"2"}]}}],"fee":{"gas":"70000","amount":[{"denom":"uatom","amount":"1000"}]},"memo":"","signatures":[{"signature":"LY2iTu+6LeMh/s6ASSRlnxJE3aSpTp6Ung0JMIbyPLF+LDI7YH7M+HRzdtc+5kx+V/8fKmWxfAZIqoyNv0Rh3g==","pub_key":{"type":"tendermint/PubKeySecp256k1","value":"A8mdavgH7MjKqgPdZ8Q9T1xihUbiiRzBqnOR5zCGA40p"},"account_number":"11335","sequence":"0"}]},"mode":"sync"}

**Comment by hukkinj1** [comment]
Hi! The node (https://stargate.cosmos.network) seems to be having some issues right now. You can try another node, for instance https://lcd.nylira.net

Note that this transaction will not be valid though, since your account (cosmos1j32hpgtzh4sudpl0658ylr2tdzu65reyy78x50) does not have any funds.

**Comment by Mahsa-Bastankhah** [comment]
can you send me the link of cosmoshub-3 faucet so I can fund my testnet address?

**Comment by hukkinj1** [comment]
Sorry, I have no idea where to find a Cosmos faucet :smile:

**Comment by Mahsa-Bastankhah** [comment]
so I should run this command ?
curl -X POST "https://lcd.nylira.net/tx" -H "accept: application/json" -H "Content-Type: application/json" -d "{ \"tx\": { \"msg\": [ {\"type\":\"cosmos-sdk/MsgSend\",\"value\":{\"from_address\":\"cosmos1j32hpgtzh4sudpl0658ylr2tdzu65reyy78x50\",\"to_address\":\"cosmos1j32hpgtzh4sudpl0658ylr2tdzu65reyy78x50\",\"amount\":[{\"denom\":\"uatom\",\"amount\":\"2\"}]}} ], \"fee\": { \"gas\": \"70000\", \"amount\": [ { \"denom\": \"uatom\", \"amount\": \"1000\" } ] }, \"memo\": \"string\", \"signature\": { \"signature\": \"LY2iTu+6LeMh/s6ASSRlnxJE3aSpTp6Ung0JMIbyPLF+LDI7YH7M+HRzdtc+5kx+V/8fKmWxfAZIqoyNv0Rh3g==\", \"pub_key\": { \"type\": \"tendermint/PubKeySecp256k1\", \"value\": \"A8mdavgH7MjKqgPdZ8Q9T1xihUbiiRzBqnOR5zCGA40p\" }, \"account_number\": \"11335\", \"sequence\": \"0\" } }, \"mode\": \"sync\"}"

this gets 404 error...

can't you send me some testnet coins?I will give you back when I didn't need it.
another question : how can I use this library to send atom transaction in the mainnet?

**Comment by hukkinj1** [comment]
> so I should run this command ?

The correct endpoint is `POST /txs` not `POST /tx`.

> can't you send me some testnet coins?I will give you back when I didn't need it.

Sorry, I don't have any.

> another question : how can I use this library to send atom transaction in the mainnet?

Exactly the way you are using it. Both of the two nodes mentioned here are mainnet nodes.

**Comment by Mahsa-Bastankhah** [comment]
> > so I should run this command ?
> 
> The correct endpoint is `POST /txs` not `POST /tx`.
> 
> > can't you send me some testnet coins?I will give you back when I didn't need it.
> 
> Sorry, I don't have any.
> 
> > another question : how can I use this library to send atom transaction in the mainnet?
> 
> Exactly the way you are using it. Both of the two nodes mentioned here are mainnet nodes.

I thought that cosmoshub-3 is testent! so how can I run code on testnet?

**Comment by hukkinj1** [comment]
> I thought that cosmoshub-3 is testent!

Nope thats mainnet.

> so how can I run code on testnet?

Replace `chain_id` with the testnets id when initializing a `cosmospy.Transaction`.

> and what is the end point for testnet?

Off the top my head I can't remember. Try Google?

**Comment by Mahsa-Bastankhah** [comment]
> > I thought that cosmoshub-3 is testent!
> 
> Nope thats mainnet.
> 
> > so how can I run code on testnet?
> 
> Replace `chain_id` with the testnets id when initializing a `cosmospy.Transaction`.
> 
> > and what is the end point for testnet?
> 
> Off the top my head I can't remember. Try Google?

as I'm new to cosmos I couldn't find that. if you found that can you kindly send me the endpoint address?

**Comment by hukkinj1** [comment]
Here's resources on cosmos testnets:
- https://github.com/cosmos/testnets
- https://hub.cosmos.network/master/gaia-tutorials/join-testnet.html

If you can't find a URL for an existing node, the docs explain how to set up a network of your own.
