### ISSUE TITLE
signature verification failed

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [hukkinj1/cosmospy#14]
I am the receiver of [this transaction](https://www.mintscan.io/cosmos/txs/76FA3F909DCDEF676C09ECF689180D6B94FD43490F3DFF4E735395E93EE819E5) and I want to spend 0.1 atom from this account. but when I run the following code I get ""signature verification failed; verify correct account sequence and chain-id" error.

curl -X POST "https://lcd.nylira.net/txs" -H "accept: application/json" -H "Content-Type: application/json" -d "{\"tx\":{\"msg\":[{\"type\":\"cosmos-sdk/MsgSend\",\"value\":{\"from_address\":\"cosmos15wa26mgeuxvtfpnqfle98wupdeeyxzdu7lff9a\",\"to_address\":\"cosmos15wa26mgeuxvtfpnqfle98wupdeeyxzdu7lff9a\",\"amount\":[{\"denom\":\"uatom\",\"amount\":\"100000\"}]}}],\"fee\":{\"gas\":\"70000\",\"amount\":[{\"denom\":\"uatom\",\"amount\":\"1000\"}]},\"memo\":\"\",\"signatures\":[{\"signature\":\"8KyuGPORRF5Eakxw5URy9BM0CjDM72pw25PuhXVBGCcZCvxZ/UIsssNR+OO9DH9JUDp89yX/RUMFvbES1MGwhA==\",\"pub_key\":{\"type\":\"tendermint/PubKeySecp256k1\",\"value\":\"A3ouexs2TMGjefw2zBWKNnwSZJgFsMYmf5OHkfwdWTWX\"},\"account_number\":\"11335\",\"sequence\":\"0\"}]},\"mode\":\"sync\"}"

since I'm sure that my signature is true,the chain-id should be wrong. I can't find the right chain-id. can you help me please?

**Comment by hukkinj1** [comment]
Hi,

your the account number you're using is incorrect

```console
foo@bar:~$ curl -X GET "https://lcd.nylira.net/auth/accounts/cosmos15wa26mgeuxvtfpnqfle98wupdeeyxzdu7lff9a" -H  "accept: application/json"
{"height":"4038809","result":{"type":"cosmos-sdk/Account","value":{"address":"cosmos15wa26mgeuxvtfpnqfle98wupdeeyxzdu7lff9a","coins":[{"denom":"uatom","amount":"500000"}],"public_key":null,"account_number":"101243","sequence":"0"}}}
```
Try using 101243
