### ISSUE TITLE
getting the average fee of the network

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [hukkinj1/cosmospy#15]
how can I get the average fee of the chain using this library or using any curl command?
I searched for this in https://cosmos.network/rpc/v0.37.9 but couldn't find any fee-related "Get" function.

**Comment by hukkinj1** [comment]
Hi,
this is not a networking library, and does not provide such functionality. AFAIK blocks have never been full on the Cosmos network and people tend to use a fixed fee.
