### ISSUE TITLE
how to get account_num and sequence

### ISSUE THREAD

**Issue by wrhwrhwrhsf** [hukkinj1/cosmospy#29]

**Comment by hukkin** [comment]
The Cosmos REST API can give these to you via an endpoint (can't remember exactly which one, pls look up in the docs).

**Comment by Bha91** [comment]
off topic of this library 
but try: `/cosmos​/auth​/v1beta1​/accounts​/{address}` for account_num and `/blocks/latest `for latest block [REF](https://v1.cosmos.network/rpc/v0.44.5)
