### ISSUE TITLE
Seed words

### ISSUE THREAD

**Issue by RaulBernal** [hukkinj1/cosmospy#7]
Can any function be implemented to deal with seed words?

**Comment by hukkinj1** [comment]
Hi @RaulBernal, that should definitely be possible.

What exactly is your use case? Do you want to import a generated wallet to some app that only takes mnemonic seeds? Or sign transactions while only knowing the mnemonic seed, not the privkey? Or perhaps something else?

**Comment by RaulBernal** [comment]
My use case is when using relayer (in IBC) I get an address from other zone: 
**$ rly keys add $CHAINID $RLYKEY**
_{"mnemonic":"pact hola guard swap early picnic example also gather clay museum attend urge always cake scorpion fashion certain exit keen olive price pelican blossom","address":"cosmos1n6hjn6fpxygxugl9fpekzhpdtqfhe2lzw4fltw"}_

If you want to handle this account in the zone you must recover it before you start manage it, in example, make a TX send to another account. 
Would it be possible to get the privkey of the  seeds directly?

**Comment by hukkinj1** [comment]
@RaulBernal FYI: I started working on this here https://github.com/hukkinj1/cosmospy/pull/8

I will add a new function called `seed_to_privkey` and make `generate_wallet` function return a mnemonic phrase as part of its return value dict.

I will hopefully release this during the upcoming week.

**Comment by RaulBernal** [comment]
Thanks, a good new for Python and Cosmos lovers

**Comment by hukkinj1** [comment]
I've released v5.0.0 on PyPI. This should now be resolved. Please see the changelog before updating https://github.com/hukkinj1/cosmospy/blob/master/CHANGELOG.md
